CREATE TYPE "Provider" AS ENUM ('samsung', 'mock');
CREATE TYPE "MovementState" AS ENUM ('MOVING', 'STOPPED', 'UNKNOWN', 'STALE', 'OFFLINE');
CREATE TYPE "TripStatus" AS ENUM ('ACTIVE', 'COMPLETED', 'DISCARDED');
CREATE TYPE "EventSeverity" AS ENUM ('INFO', 'WARNING', 'ERROR');
CREATE TABLE "User" ("id" TEXT PRIMARY KEY, "email" TEXT NOT NULL UNIQUE, "name" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Device" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL REFERENCES "User"("id") ON DELETE CASCADE, "provider" "Provider" NOT NULL, "providerDeviceId" TEXT NOT NULL, "deviceName" TEXT NOT NULL, "model" TEXT, "enabled" BOOLEAN NOT NULL DEFAULT true, "lastSeenAt" TIMESTAMP(3), "movementState" "MovementState" NOT NULL DEFAULT 'UNKNOWN', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "LocationPoint" ("id" TEXT PRIMARY KEY, "deviceId" TEXT NOT NULL REFERENCES "Device"("id") ON DELETE CASCADE, "latitude" DECIMAL(10,7) NOT NULL, "longitude" DECIMAL(10,7) NOT NULL, "accuracy" DOUBLE PRECISION, "providerTimestamp" TIMESTAMP(3), "collectedAt" TIMESTAMP(3) NOT NULL, "source" "Provider" NOT NULL, "state" "MovementState" NOT NULL DEFAULT 'UNKNOWN', "speedEstimate" DOUBLE PRECISION, "distanceFromPrevious" DOUBLE PRECISION, "rawStatus" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "Stop" ("id" TEXT PRIMARY KEY, "deviceId" TEXT NOT NULL REFERENCES "Device"("id") ON DELETE CASCADE, "latitude" DECIMAL(10,7) NOT NULL, "longitude" DECIMAL(10,7) NOT NULL, "startedAt" TIMESTAMP(3) NOT NULL, "endedAt" TIMESTAMP(3), "durationSeconds" INTEGER NOT NULL, "radiusMeters" DOUBLE PRECISION NOT NULL, "address" TEXT, "placeName" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Trip" ("id" TEXT PRIMARY KEY, "deviceId" TEXT NOT NULL REFERENCES "Device"("id") ON DELETE CASCADE, "startedAt" TIMESTAMP(3) NOT NULL, "endedAt" TIMESTAMP(3), "startLatitude" DECIMAL(10,7) NOT NULL, "startLongitude" DECIMAL(10,7) NOT NULL, "endLatitude" DECIMAL(10,7), "endLongitude" DECIMAL(10,7), "distanceMeters" DOUBLE PRECISION NOT NULL DEFAULT 0, "durationSeconds" INTEGER NOT NULL DEFAULT 0, "estimatedRouteDistanceMeters" DOUBLE PRECISION, "status" "TripStatus" NOT NULL DEFAULT 'ACTIVE', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "GeocodedPlace" ("id" TEXT PRIMARY KEY, "deviceId" TEXT NOT NULL REFERENCES "Device"("id") ON DELETE CASCADE, "latitudeKey" DECIMAL(8,4) NOT NULL, "longitudeKey" DECIMAL(8,4) NOT NULL, "latitude" DECIMAL(10,7) NOT NULL, "longitude" DECIMAL(10,7) NOT NULL, "name" TEXT, "address" TEXT, "visitCount" INTEGER NOT NULL DEFAULT 1, "lastVisitedAt" TIMESTAMP(3) NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "SystemEvent" ("id" TEXT PRIMARY KEY, "type" TEXT NOT NULL, "severity" "EventSeverity" NOT NULL DEFAULT 'INFO', "message" TEXT NOT NULL, "metadata" JSONB, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "Device_provider_providerDeviceId_key" ON "Device"("provider", "providerDeviceId");
CREATE INDEX "Device_userId_idx" ON "Device"("userId");
CREATE INDEX "LocationPoint_deviceId_idx" ON "LocationPoint"("deviceId");
CREATE INDEX "LocationPoint_providerTimestamp_idx" ON "LocationPoint"("providerTimestamp");
CREATE INDEX "LocationPoint_collectedAt_idx" ON "LocationPoint"("collectedAt");
CREATE INDEX "LocationPoint_deviceId_collectedAt_idx" ON "LocationPoint"("deviceId", "collectedAt");
CREATE UNIQUE INDEX "LocationPoint_deviceId_providerTimestamp_latitude_longitude_key" ON "LocationPoint"("deviceId", "providerTimestamp", "latitude", "longitude");
CREATE INDEX "Stop_deviceId_startedAt_idx" ON "Stop"("deviceId", "startedAt");
CREATE INDEX "Trip_deviceId_startedAt_idx" ON "Trip"("deviceId", "startedAt");
CREATE UNIQUE INDEX "GeocodedPlace_deviceId_latitudeKey_longitudeKey_key" ON "GeocodedPlace"("deviceId", "latitudeKey", "longitudeKey");
CREATE INDEX "SystemEvent_type_createdAt_idx" ON "SystemEvent"("type", "createdAt");
CREATE INDEX "SystemEvent_createdAt_idx" ON "SystemEvent"("createdAt");
